apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-devops
  template:
    metadata:
      labels:
        app: hello-devops
    spec:
      containers:
      - name: app
        image: hello-devops:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-devops-service
spec:
  type: NodePort
  selector:
    app: hello-devops
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000