steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-python@v4
    with:
      python-version: '3.9'
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r infra/requirements.txt
  - name: Run tests
    run: |
      export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
      pytest tests/
  - name: Run Pipeline
    run: |
      export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
      python ci_cd_pipeline.py